services:
  svelte:
    image: jensr22/eshop_svelte
    restart: unless-stopped
    ports:
      - "3002:3000"
    environment:
      - API_URL=https://eshop.jensramakers.nl
      - PUBLIC_API_URL=https://eshop.jensramakers.nl
  userservice:
    image: jensr22/eshop_userservice
    restart: unless-stopped
    ports:
      - "5207:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres:5432;Database=eshop_userservice;Username=postgres;Password=postgres;
      - Kafka__Server=kafka:9092
      - Kafka__GroupId=userservice-consumer-group
      - Jwt__Key=YourSecretKeyForAuthenticationOfApplication
      - Jwt__Issuer=yourCompanyIssuer.com
      - Jwt__Audience=yourCompanyAudience.com
      - Jwt__ExpiresIn=3600
      - Jwt__RefreshTokenExpiresIn=2592000
      - Logging__LogLevel__Default=Information
      - Logging__LogLevel__Microsoft.AspNetCore=Warning
      - AllowedHosts=*
  cartservice:
    image: jensr22/eshop_cartservice
    restart: unless-stopped
    ports:
      - "5074:8080"
    environment:
      - ApiUrlProductService=http://productservice:8080
      - Kafka__Server=kafka:9092
      - Kafka__GroupId=cartservice-consumer-group
      - Jwt__Key=YourSecretKeyForAuthenticationOfApplication
      - Jwt__Issuer=yourCompanyIssuer.com
      - Jwt__Audience=yourCompanyAudience.com
      - Jwt__ExpiresIn=3600
      - eshop_cartservice__ConnectionString=mongodb://mongodb:27017
      - eshop_cartservice__DatabaseName=eshop_cartservice
      - eshop_cartservice__CartItemsCollectionName=CartItems
      - Logging__LogLevel__Default=Information
      - Logging__LogLevel__Microsoft.AspNetCore=Warning
      - AllowedHosts=*
  orderservice:
    image: jensr22/eshop_orderservice
    restart: unless-stopped
    ports:
      - "5278:8080"
    environment:
      - FrontendUrls=http://localhost:5173,http://172.17.0.1:5173,http://eshop.jensramakers.nl,https://eshop.jensramakers.nl
      - ApiUrlCartService=http://cartservice:8080
      - Kafka__Server=kafka:9092
      - Kafka__GroupId=orderservice-consumer-group
      - Jwt__Key=YourSecretKeyForAuthenticationOfApplication
      - Jwt__Issuer=yourCompanyIssuer.com
      - Jwt__Audience=yourCompanyAudience.com
      - Jwt__ExpiresIn=3600
      - eshop_orderservice__ConnectionString=mongodb://mongodb:27017
      - eshop_orderservice__DatabaseName=eshop_orderservice
      - eshop_orderservice__OrdersCollectionName=Orders
      - Logging__LogLevel__Default=Information
      - Logging__LogLevel__Microsoft.AspNetCore=Warning
      - AllowedHosts=*
  productservice:
    image: jensr22/eshop_productservice
    restart: unless-stopped
    ports:
      - "5077:8080"
    environment:
      - FrontendUrls=http://localhost:5173,http://172.17.0.1:5173,http://eshop.jensramakers.nl,https://eshop.jensramakers.nl
      - TypeSense__Host=typesense
      - TypeSense__ApiKey=xyz
      - TypeSense__Protocol=http
      - TypeSense__Port=8108
      - Kafka__Server=kafka:9092
      - Kafka__GroupId=productservice-consumer-group
      - Jwt__Key=YourSecretKeyForAuthenticationOfApplication
      - Jwt__Issuer=yourCompanyIssuer.com
      - Jwt__Audience=yourCompanyAudience.com
      - Jwt__ExpiresIn=3600
      - ConnectionStrings__DefaultConnection=Host=postgres:5432;Database=eshop_productservice;Username=postgres;Password=postgres;
      - Logging__LogLevel__Default=Information
      - Logging__LogLevel__Microsoft.AspNetCore=Warning
      - AllowedHosts=*
#      - ASPNETCORE_ENVIRONMENT=Development
    deploy:
      resources:
        limits:
          memory: 256M

  postgres:
    image: postgres:17
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/17/docker
    volumes:
      - /mnt/4tb1/eshop_docker_data_prod/postgres:/var/lib/postgresql/17/docker

  mongodb:
    image: mongo:8.0
    restart: unless-stopped
    ports:
      - "27018:27017"
    volumes:
      - /mnt/4tb1/eshop_docker_data_prod/mongo:/data/db

  kafka:
    image: jensr22/bitnami_kafka:3.9
    restart: unless-stopped
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_LISTENERS=INTERNAL://:9092,EXTERNAL_HOST://:9094,EXTERNAL_MINIKUBE://:9095,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka:9092,EXTERNAL_HOST://localhost:9094,EXTERNAL_MINIKUBE://172.17.0.1:9095
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL_HOST:PLAINTEXT,EXTERNAL_MINIKUBE:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_NUM_PARTITIONS=1
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - "9092:9092"
      - "9093:9093"
      - "9094:9094"
      - "9095:9095"
    volumes:
      - /mnt/4tb1/eshop_docker_data_prod/kafka:/bitnami/kafka
    deploy:
      resources:
        limits:
          memory: 512M

#  nginx:
#    image: nginx:latest
#    restart: unless-stopped
#    ports:
#      - "81:80"
#    volumes:
#      - ./dockerFiles/nginx.conf:/etc/nginx/conf.d/default.conf
  
  typesense:
    image: typesense/typesense:29.0
    restart: unless-stopped
    volumes:
      - /mnt/4tb1/eshop_docker_data_prod/typesense-data:/data
    ports:
      - 8108:8108
    #For production remove interval this will default to 3600 seconds
    command: '--data-dir /data --api-key=xyz --enable-cors --cors-domains=http://localhost:8188 --enable-search-analytics=true --analytics-dir=/data/analytics --analytics-flush-interval=60'
    deploy:
      resources:
        limits:
          memory: 1G