services:
  postgres_userservice:
    image: postgres:17
    container_name: eshop-postgres-userservice
    restart: on-failure
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/17/docker
    volumes:
      - ./data_postgres_userservice:/var/lib/postgresql/17/docker

  postgres_productservice:
    image: postgres:17
    container_name: eshop-postgres-productservice
    restart: on-failure
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/17/docker
    volumes:
      - ./data_postgres_productservice:/var/lib/postgresql/17/docker
  
  # login (system: PostgreSQL, server: postgres, username: postgres, password: postgres, database: postgres)
  adminer:
    image: adminer
    restart: on-failure
    ports:
      - "8082:8080"
  
  # mysql:
  #   image: mysql:8.0.36
  #   container_name: eshop-mysql
  #   restart: on-failure
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=password
  #     - MYSQL_USER=user
  #     - MYSQL_PASSWORD=password
  #   volumes:
  #     - ./data:/var/lib/mysql

  # phpmyadmin:
  #   image: jensr22/phpmyadmin:latest
  #   container_name: eshop-phpmyadmin
  #   restart: on-failure
  #   ports:
  #     - "8080:80"
  #   environment:
  #     - PMA_ARBITRARY=1
  #     - PMA_HOST=mysql
  #     - PMA_USER=root
  #     - PMA_PASSWORD=password

  mongodb:
    image: mongo:8.0
    container_name: eshop-mongodb
    restart: on-failure
    ports:
      - "27017:27017"

  compass:
    image: haohanyang/compass-web
    container_name: eshop-compass
    restart: on-failure
    environment:
      - CW_MONGO_URI=mongodb://mongodb:27017
    ports:
      - "8083:8080"

  mongo-express:
    image: mongo-express
    container_name: eshop-mongo-express
    restart: on-failure
    ports:
      - 8085:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/
      ME_CONFIG_BASICAUTH_ENABLED: false
#      ME_CONFIG_BASICAUTH_USERNAME: mongoexpressuser
#      ME_CONFIG_BASICAUTH_PASSWORD: mongoexpresspass

  kafka:
    image: bitnami/kafka:3.9
    container_name: eshop-kafka
    restart: on-failure
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_LISTENERS=INTERNAL://:9092,EXTERNAL_HOST://:9094,EXTERNAL_MINIKUBE://:9095,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka:9092,EXTERNAL_HOST://localhost:9094,EXTERNAL_MINIKUBE://host.minikube.internal:9095
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL_HOST:PLAINTEXT,EXTERNAL_MINIKUBE:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_NUM_PARTITIONS=1
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - "9092:9092"
      - "9093:9093"
      - "9094:9094"
      - "9095:9095"
    volumes:
      - ./data_kafka:/bitnami/kafka

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: eshop-kafka-ui
    restart: on-failure
    depends_on:
      - kafka
    ports:
      - "8081:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092

  nginx:
    image: nginx:latest
    container_name: eshop-nginx-proxy
    restart: on-failure
    ports:
      - "80:80"
    volumes:
      - ./dockerFiles/nginx.conf:/etc/nginx/conf.d/default.conf
  
  typesense:
    image: typesense/typesense:29.0
    container_name: eshop-productservice-typesense
    restart: on-failure
    volumes:
      - ./typesense-data:/data
    ports:
      - 8108:8108
    #For production remove interval this will default to 3600 seconds
    command: '--data-dir /data --api-key=xyz --enable-cors --cors-domains=http://localhost:8188 --enable-search-analytics=true --analytics-dir=/data/analytics --analytics-flush-interval=60'

  typesense_dashboard:
    image: ghcr.io/bfritscher/typesense-dashboard:latest
    container_name: eshop-productservice-typesense_dashboard
    restart: on-failure
    volumes:
      - ./typesense-dashboard/config.json:/srv/config.json
    ports:
      - 8188:80